//package com.cfs.payment_gateway.entity;
//import jakarta.persistence.*;
//import java.time.LocalDateTime;
//
///**
// * JPA Entity representing a payment order record in the database.
// * This tracks the status and details of each transaction.
// * (Based on screenshot 2.57.22 PM.jpeg)
// */
//@Entity
//@Table(name = "payment_order")
//public class PaymentOrder{
//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    // The order ID generated by Razorpay
//    private String orderId;
//
//    // The payment ID received from Razorpay after successful payment (for update-order)
//    private String paymentId;
//
//    // Status of the payment (e.g., "CREATED", "SUCCESS", "FAILED")
//    private String status;
//
//    // The total amount of the order
//    private double amount;
//
//    // A receipt number or merchant transaction ID
//    private String receipt;
//
//    // Timestamp when the order was created
//    private LocalDateTime createdAt;
//
//    // Default constructor
//    public PaymentOrder() {}
//
//    // --- Getters and Setters ---
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public String getOrderId() {
//        return orderId;
//    }
//
//    public void setOrderId(String orderId) {
//        this.orderId = orderId;
//    }
//
//    public String getPaymentId() {
//        return paymentId;
//    }
//
//    public void setPaymentId(String paymentId) {
//        this.paymentId = paymentId;
//    }
//
//    public String getStatus() {
//        return status;
//    }
//
//    public void setStatus(String status) {
//        this.status = status;
//    }
//
//    public double getAmount() {
//        return amount;
//    }
//
//    public void setAmount(double amount) {
//        this.amount = amount;
//    }
//
//    public String getReceipt() {
//        return receipt;
//    }
//
//    public void setReceipt(String receipt) {
//        this.receipt = receipt;
//    }
//
//    public LocalDateTime getCreatedAt() {
//        return createdAt;
//    }
//
//    public void setCreatedAt(LocalDateTime createdAt) {
//        this.createdAt = createdAt;
//    }
//}


package com.cfs.payment_gateway.entity;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * JPA Entity representing a payment order record in the database.
 * This tracks the status and details of each transaction.
 */
@Entity
@Table(name = "payment_order")
public class PaymentOrder{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The order ID generated by Razorpay
    private String orderId;

    // The payment ID received from Razorpay after successful payment (for update-order)
    private String paymentId;

    // Status of the payment (e.g., "CREATED", "SUCCESS", "FAILED")
    private String status;

    // The total amount of the order
    private double amount;

    // A receipt number or merchant transaction ID
    private String receipt;

    // --- NEW FIELDS ADDED FOR EMAIL SERVICE INTEGRATION ---

    // Email of the learner/customer
    private String email;

    // Name of the course purchased
    private String courseName;

    // --- END NEW FIELDS ---

    // Timestamp when the order was created
    private LocalDateTime createdAt;

    // Default constructor
    public PaymentOrder() {}

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getReceipt() {
        return receipt;
    }

    public void setReceipt(String receipt) {
        this.receipt = receipt;
    }

    // --- NEW GETTERS AND SETTERS ---

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    // --- END NEW GETTERS AND SETTERS ---

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}